version: '3.8'

services:
  tedioapp:
    image: jessebezerra/tedioapp:latest
    container_name: tedioapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
